apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-test
  template:
    metadata:
      labels:
        app: my-app-test
      annotations:
        force-update: "now"  # 🔁 аннотация для "вынужденного" обновления
    spec:
      containers:
      - name: my-app
        image: my-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
